set_value:
  name: Set value
  description: Set a numeric value on the stove.
  fields:
    entity_id:
      name: Entity
      description: Entity to set the value for
      required: true
      selector:
        entity:
          domain: sensor
    value:
      name: Value
      description: Value to set
      required: true
      selector:
        number:
          min: 0
          max: 10
          step: 1
